3.	baseURL: "https://minakao.github.io/abap/"
4.	title: ABAP 技術筆記
5.	paginate: 5
6.	theme: PaperMod
7.	
8.	enableRobotsTXT: true
9.	buildDrafts: false
10.	buildFuture: false
11.	buildExpired: false
12.	
13.	googleAnalytics: "" # Put your google analytics code here, and it will collect data
14.	
15.	minify:
16.	  disableXML: true
17.	  minifyOutput: true
18.	
19.	params:
20.	  env: production # to enable google analytics, opengraph, twitter-cards and schema.
21.	  title: Mina ABAP Codes Blog - Software Engineering Tutorials
22.	  description: "The Blog for the ABAP Codes, "
23.	  keywords: [Blog, ABAP, PaperMod]
24.	  author: Mina
25.	  # author: ["Me", "You"] # multiple authors
26.	  DateFormat: "January 2, 2026"
27.	  defaultTheme: auto # dark, light
28.	  disableThemeToggle: false
29.	
30.	  ShowReadingTime: true
31.	  ShowShareButtons: true
32.	  ShowPostNavLinks: true
33.	  ShowBreadCrumbs: true
34.	  ShowCodeCopyButtons: true
35.	  ShowWordCount: true
36.	  ShowRssButtonInSectionTermList: false
37.	  UseHugoToc: true
38.	  disableSpecial1stPost: false
39.	  disableScrollToTop: false
40.	  comments: false
41.	  hidemeta: false
42.	  hideSummary: false
43.	  showtoc: false
44.	  tocopen: false
45.	
46.	  assets:
47.	    favicon: "/favicon.ico"
48.	    favicon16x16: "/favicon-16x16.png"
49.	    favicon32x32: "/favicon-32x32.png"
50.	    apple_touch_icon: "/apple-touch-icon.png"
51.	    safari_pinned_tab: "/apple-touch-icon.png"
52.	
53.	  label:
54.	    text: "ABAP Codes Blog"
55.	    icon: /favicon-32x32.png
56.	    iconHeight: 25
57.	
58.	  # home-info mode
59.	  homeInfoParams:
60.	    Title: "What's going on, It's Mina Codes!"
61.	    Content: On this blog I discuss a bunch of things related to technology, feel free to look around!
62.	
63.	  socialIcons:
64.	    - name: youtube
65.	      url: "https://minakao.github.io/abap/"
66.	    - name: x
67.	      url: "https://minakao.github.io/abap/"
68.	    - name: github
69.	      url: "https://minakao.github.io/abap/"
70.	
71.	menu:
72.	  main:
73.	    - identifier: tags
74.	      name: tags
75.	      url: /tags/
76.	      weight: 20
77.	    
78.	pygmentsCodeFences: true   
79.	pygmentsUseClasses: false
80.	
81.	markup:
82.	    goldmark:
83.	        renderer:
84.	            unsafe: true
85.	    highlight:
86.	        noClasses: true
87.	        # anchorLineNos: true
88.	        codeFences: true
89.	        guessSyntax: true
90.	        # lineNos: true
91.	        style: monokai
